apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:32000/frontend:1.1.2
        ports:
        - containerPort: 3000
          name: frontend-port
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-port
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      name: frontend-port
      nodePort: 30000
  selector:
    app: frontend-deployment